define(["httprequest", 
			  "socket",
				"src/connection/pool",
				"src/connection/queue",
				"src/connection/race",
				"src/connection/symfony",
				"src/model/base",
				"src/collection/base",
				"src/collection/persistence",
				"src/serializer/base",
				"src/serializer/bracket",
				"src/serializer/json",
				"src/view/base",
				"src/view/formdelegate",
				"src/view/symfonyformdelegate"],
				function(HttpRequest,
								 ConnectionPool,
								 HttpQueue,
								 HttpRace,
								 Socket,
								 SymfonyRequest,
								 BaseModel,
								 PersistenceCollection,
								 PlainSerializer,
								 BracketSerializer,
								 JsonSerializer,
								 BaseView,
								 FormView,
								 SymfonyForm){

					return {
						"HttpRequest" : HttpRequest,
						"ConnectionPool" : ConnectionPool,
						"HttpQueue" : HttpQueue,
						"HttpRace" : HttpRace,
						"Socket" : Socket,
						"SymfonyRequest" : SymfonyRequest,
						"BaseModel" : BaseModel,
						"PersistenceCollection" : PersistenceCollection,
						"PlainSerializer" : PlainSerializer,
						"BracketSerializer" : BracketSerializer,
						"JsonSerializer" : JsonSerializer,
						"BaseView" : BaseView,
						"FormView" : FormView,
						"SymfonyForm" : SymfonyForm
					};

		});